spring.application.name=myCoolApp

management.endpoints.web.exposure.include = *
management.info.env.enable = true

#Excluding individual endpoints

info.app.name = My super cool App
info.app.description = a crazy fun app, yooohooo!
info.app.version = 1.0.0


#
#define my crazy properties
#

coach.name = Mickey Mouse
team.name = The Mouse Club

#
#configuring the server port
#

server.port = 7070
#
#changing app context path with /mycoolapp
#

server.servlet.context-path = /mycoolapp
